"""require business profile ownership for users

Revision ID: 13dcf814299c
Revises: d6a4036401fd
Create Date: 2026-05-26 18:17:22.772560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '13dcf814299c'
down_revision: Union[str, Sequence[str], None] = 'd6a4036401fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'business_profile_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'business_profile_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
