"""add daily shifts

Revision ID: 1d436536cb7a
Revises: 9b54ab28478e
Create Date: 2026-06-15 11:56:24.079882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d436536cb7a'
down_revision: Union[str, Sequence[str], None] = '9b54ab28478e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_profile_id', sa.Integer(), nullable=False),
    sa.Column('shift_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_by_user_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_by_user_id', sa.Integer(), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['business_profile_id'], ['business_profiles.id'], ),
    sa.ForeignKeyConstraint(['ended_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['started_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_profile_id', 'shift_date', name='uq_daily_shifts_business_profile_date')
    )
    op.create_index(op.f('ix_daily_shifts_business_profile_id'), 'daily_shifts', ['business_profile_id'], unique=False)
    op.create_index(op.f('ix_daily_shifts_id'), 'daily_shifts', ['id'], unique=False)
    op.create_index(op.f('ix_daily_shifts_shift_date'), 'daily_shifts', ['shift_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_shifts_shift_date'), table_name='daily_shifts')
    op.drop_index(op.f('ix_daily_shifts_id'), table_name='daily_shifts')
    op.drop_index(op.f('ix_daily_shifts_business_profile_id'), table_name='daily_shifts')
    op.drop_table('daily_shifts')
    # ### end Alembic commands ###
