"""add business chilling equipment

Revision ID: 4c79c78e07c2
Revises: 1d436536cb7a
Create Date: 2026-06-22 13:16:56.087750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c79c78e07c2'
down_revision: Union[str, Sequence[str], None] = '1d436536cb7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_chilling_equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_profile_id', sa.Integer(), nullable=False),
    sa.Column('source_safety_point_id', sa.String(length=50), nullable=False),
    sa.Column('equipment_name', sa.String(length=255), nullable=False),
    sa.Column('equipment_use', sa.String(length=50), nullable=False),
    sa.Column('equipment_type', sa.String(length=50), nullable=False),
    sa.Column('temperature_check_method', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_profile_id'], ['business_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_chilling_equipment_business_profile_id'), 'business_chilling_equipment', ['business_profile_id'], unique=False)
    op.create_index(op.f('ix_business_chilling_equipment_id'), 'business_chilling_equipment', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_business_chilling_equipment_id'), table_name='business_chilling_equipment')
    op.drop_index(op.f('ix_business_chilling_equipment_business_profile_id'), table_name='business_chilling_equipment')
    op.drop_table('business_chilling_equipment')
    # ### end Alembic commands ###
