"""add chilling temperature incidents and shift diary entries

Revision ID: 63bedd919209
Revises: ff632b7fdb1d
Create Date: 2026-06-30 17:05:56.032321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63bedd919209'
down_revision: Union[str, Sequence[str], None] = 'ff632b7fdb1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_diary_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_profile_id', sa.Integer(), nullable=False),
    sa.Column('daily_shift_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('entry_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('entry_text', sa.Text(), nullable=False),
    sa.Column('related_entity_type', sa.String(length=100), nullable=True),
    sa.Column('related_entity_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_profile_id'], ['business_profiles.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['daily_shift_id'], ['daily_shifts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_diary_entries_business_profile_id'), 'shift_diary_entries', ['business_profile_id'], unique=False)
    op.create_index(op.f('ix_shift_diary_entries_created_by_user_id'), 'shift_diary_entries', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_shift_diary_entries_daily_shift_id'), 'shift_diary_entries', ['daily_shift_id'], unique=False)
    op.create_index(op.f('ix_shift_diary_entries_entry_type'), 'shift_diary_entries', ['entry_type'], unique=False)
    op.create_index(op.f('ix_shift_diary_entries_id'), 'shift_diary_entries', ['id'], unique=False)
    op.create_table('chilling_temperature_incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_profile_id', sa.Integer(), nullable=False),
    sa.Column('daily_shift_id', sa.Integer(), nullable=False),
    sa.Column('chilling_temperature_check_id', sa.Integer(), nullable=False),
    sa.Column('chilling_equipment_id', sa.Integer(), nullable=False),
    sa.Column('check_period', sa.String(length=20), nullable=False),
    sa.Column('equipment_asset_code_snapshot', sa.String(length=50), nullable=False),
    sa.Column('equipment_name_snapshot', sa.String(length=255), nullable=False),
    sa.Column('equipment_type_snapshot', sa.String(length=50), nullable=False),
    sa.Column('recorded_temperature', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('compliance_threshold', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('recorded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_profile_id'], ['business_profiles.id'], ),
    sa.ForeignKeyConstraint(['chilling_equipment_id'], ['business_chilling_equipment.id'], ),
    sa.ForeignKeyConstraint(['chilling_temperature_check_id'], ['daily_shift_chilling_temperature_checks.id'], ),
    sa.ForeignKeyConstraint(['daily_shift_id'], ['daily_shifts.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chilling_temperature_check_id', 'check_period', name='uq_chilling_temp_incident_check_period')
    )
    op.create_index(op.f('ix_chilling_temperature_incidents_business_profile_id'), 'chilling_temperature_incidents', ['business_profile_id'], unique=False)
    op.create_index(op.f('ix_chilling_temperature_incidents_chilling_equipment_id'), 'chilling_temperature_incidents', ['chilling_equipment_id'], unique=False)
    op.create_index(op.f('ix_chilling_temperature_incidents_chilling_temperature_check_id'), 'chilling_temperature_incidents', ['chilling_temperature_check_id'], unique=False)
    op.create_index(op.f('ix_chilling_temperature_incidents_daily_shift_id'), 'chilling_temperature_incidents', ['daily_shift_id'], unique=False)
    op.create_index(op.f('ix_chilling_temperature_incidents_id'), 'chilling_temperature_incidents', ['id'], unique=False)
    op.create_index(op.f('ix_chilling_temperature_incidents_recorded_by_user_id'), 'chilling_temperature_incidents', ['recorded_by_user_id'], unique=False)
    op.create_index(op.f('ix_chilling_temperature_incidents_status'), 'chilling_temperature_incidents', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chilling_temperature_incidents_status'), table_name='chilling_temperature_incidents')
    op.drop_index(op.f('ix_chilling_temperature_incidents_recorded_by_user_id'), table_name='chilling_temperature_incidents')
    op.drop_index(op.f('ix_chilling_temperature_incidents_id'), table_name='chilling_temperature_incidents')
    op.drop_index(op.f('ix_chilling_temperature_incidents_daily_shift_id'), table_name='chilling_temperature_incidents')
    op.drop_index(op.f('ix_chilling_temperature_incidents_chilling_temperature_check_id'), table_name='chilling_temperature_incidents')
    op.drop_index(op.f('ix_chilling_temperature_incidents_chilling_equipment_id'), table_name='chilling_temperature_incidents')
    op.drop_index(op.f('ix_chilling_temperature_incidents_business_profile_id'), table_name='chilling_temperature_incidents')
    op.drop_table('chilling_temperature_incidents')
    op.drop_index(op.f('ix_shift_diary_entries_id'), table_name='shift_diary_entries')
    op.drop_index(op.f('ix_shift_diary_entries_entry_type'), table_name='shift_diary_entries')
    op.drop_index(op.f('ix_shift_diary_entries_daily_shift_id'), table_name='shift_diary_entries')
    op.drop_index(op.f('ix_shift_diary_entries_created_by_user_id'), table_name='shift_diary_entries')
    op.drop_index(op.f('ix_shift_diary_entries_business_profile_id'), table_name='shift_diary_entries')
    op.drop_table('shift_diary_entries')
    # ### end Alembic commands ###
