"""add approved safety point responses

Revision ID: 9b54ab28478e
Revises: b7496536fc29
Create Date: 2026-06-04 12:36:16.236791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b54ab28478e'
down_revision: Union[str, Sequence[str], None] = 'b7496536fc29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approved_safety_point_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('approved_safety_point_id', sa.Integer(), nullable=False),
    sa.Column('question_key', sa.String(length=100), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['approved_safety_point_id'], ['approved_safety_points.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approved_safety_point_responses_approved_safety_point_id'), 'approved_safety_point_responses', ['approved_safety_point_id'], unique=False)
    op.create_index(op.f('ix_approved_safety_point_responses_id'), 'approved_safety_point_responses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approved_safety_point_responses_id'), table_name='approved_safety_point_responses')
    op.drop_index(op.f('ix_approved_safety_point_responses_approved_safety_point_id'), table_name='approved_safety_point_responses')
    op.drop_table('approved_safety_point_responses')
    # ### end Alembic commands ###
