"""add ON DELETE CASCADE to password_reset_tokens.user_id

Revision ID: ccffbbfb60fc
Revises: 0cfdc5821820
Create Date: 2026-04-30 14:22:53.641451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccffbbfb60fc'
down_revision: Union[str, Sequence[str], None] = '0cfdc5821820'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('password_reset_tokens_ibfk_1'), 'password_reset_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'password_reset_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'password_reset_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('password_reset_tokens_ibfk_1'), 'password_reset_tokens', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
