"""require site name for business profiles

Revision ID: d6a4036401fd
Revises: 0d87adab5ba6
Create Date: 2026-05-26 15:54:02.235276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd6a4036401fd'
down_revision: Union[str, Sequence[str], None] = '0d87adab5ba6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(
        sa.text(
            """
            UPDATE business_profiles
            SET site_name = business_name
            WHERE site_name IS NULL
            """
        )
    )

    op.alter_column(
        "business_profiles",
        "site_name",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=255),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('business_profiles', 'site_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True)
    # ### end Alembic commands ###
