"""add chilling temperature corrective actions

Revision ID: dad3f6d2274a
Revises: 63bedd919209
Create Date: 2026-07-03 11:01:35.422734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dad3f6d2274a'
down_revision: Union[str, Sequence[str], None] = '63bedd919209'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chilling_temperature_corrective_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('business_profile_id', sa.Integer(), nullable=False),
    sa.Column('daily_shift_id', sa.Integer(), nullable=False),
    sa.Column('recorded_by_user_id', sa.Integer(), nullable=False),
    sa.Column('final_narrative', sa.Text(), nullable=False),
    sa.Column('structured_facts_json', sa.Text(), nullable=True),
    sa.Column('validation_status', sa.String(length=30), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_profile_id'], ['business_profiles.id'], ),
    sa.ForeignKeyConstraint(['daily_shift_id'], ['daily_shifts.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['chilling_temperature_incidents.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', name='uq_chilling_temp_corrective_action_incident')
    )
    op.create_index(op.f('ix_chilling_temperature_corrective_actions_business_profile_id'), 'chilling_temperature_corrective_actions', ['business_profile_id'], unique=False)
    op.create_index(op.f('ix_chilling_temperature_corrective_actions_daily_shift_id'), 'chilling_temperature_corrective_actions', ['daily_shift_id'], unique=False)
    op.create_index(op.f('ix_chilling_temperature_corrective_actions_id'), 'chilling_temperature_corrective_actions', ['id'], unique=False)
    op.create_index(op.f('ix_chilling_temperature_corrective_actions_recorded_by_user_id'), 'chilling_temperature_corrective_actions', ['recorded_by_user_id'], unique=False)
    op.create_index(op.f('ix_chilling_temperature_corrective_actions_validation_status'), 'chilling_temperature_corrective_actions', ['validation_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chilling_temperature_corrective_actions_validation_status'), table_name='chilling_temperature_corrective_actions')
    op.drop_index(op.f('ix_chilling_temperature_corrective_actions_recorded_by_user_id'), table_name='chilling_temperature_corrective_actions')
    op.drop_index(op.f('ix_chilling_temperature_corrective_actions_id'), table_name='chilling_temperature_corrective_actions')
    op.drop_index(op.f('ix_chilling_temperature_corrective_actions_daily_shift_id'), table_name='chilling_temperature_corrective_actions')
    op.drop_index(op.f('ix_chilling_temperature_corrective_actions_business_profile_id'), table_name='chilling_temperature_corrective_actions')
    op.drop_table('chilling_temperature_corrective_actions')
    # ### end Alembic commands ###
