"""add onboarding models

Revision ID: f50b0a6c43e2
Revises: ccffbbfb60fc
Create Date: 2026-05-07 11:49:59.089685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f50b0a6c43e2'
down_revision: Union[str, Sequence[str], None] = 'ccffbbfb60fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('site_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_profiles_id'), 'business_profiles', ['id'], unique=False)
    op.create_table('conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condition_id', sa.String(length=50), nullable=False),
    sa.Column('condition_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_condition_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conditions_condition_id'), 'conditions', ['condition_id'], unique=True)
    op.create_index(op.f('ix_conditions_id'), 'conditions', ['id'], unique=False)
    op.create_table('approved_safety_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_profile_id', sa.Integer(), nullable=False),
    sa.Column('safety_point_id', sa.String(length=50), nullable=False),
    sa.Column('safe_method_id', sa.String(length=50), nullable=False),
    sa.Column('safe_method_name', sa.String(length=255), nullable=False),
    sa.Column('safety_point_text', sa.Text(), nullable=False),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['business_profile_id'], ['business_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approved_safety_points_id'), 'approved_safety_points', ['id'], unique=False)
    op.create_index(op.f('ix_approved_safety_points_safety_point_id'), 'approved_safety_points', ['safety_point_id'], unique=False)
    op.create_table('condition_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_profile_id', sa.Integer(), nullable=False),
    sa.Column('condition_id', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['business_profile_id'], ['business_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_condition_values_condition_id'), 'condition_values', ['condition_id'], unique=False)
    op.create_index(op.f('ix_condition_values_id'), 'condition_values', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_condition_values_id'), table_name='condition_values')
    op.drop_index(op.f('ix_condition_values_condition_id'), table_name='condition_values')
    op.drop_table('condition_values')
    op.drop_index(op.f('ix_approved_safety_points_safety_point_id'), table_name='approved_safety_points')
    op.drop_index(op.f('ix_approved_safety_points_id'), table_name='approved_safety_points')
    op.drop_table('approved_safety_points')
    op.drop_index(op.f('ix_conditions_id'), table_name='conditions')
    op.drop_index(op.f('ix_conditions_condition_id'), table_name='conditions')
    op.drop_table('conditions')
    op.drop_index(op.f('ix_business_profiles_id'), table_name='business_profiles')
    op.drop_table('business_profiles')
    # ### end Alembic commands ###
