"""drop parent_condition_id from conditions

Revision ID: f82243724555
Revises: f50b0a6c43e2
Create Date: 2026-05-12 10:19:57.957272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f82243724555'
down_revision: Union[str, Sequence[str], None] = 'f50b0a6c43e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conditions', 'parent_condition_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conditions', sa.Column('parent_condition_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True))
    # ### end Alembic commands ###
