"""add corrective action sessions

Revision ID: fc54f9e0c306
Revises: dad3f6d2274a
Create Date: 2026-07-03 12:06:15.591085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc54f9e0c306'
down_revision: Union[str, Sequence[str], None] = 'dad3f6d2274a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chilling_temperature_corrective_action_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('business_profile_id', sa.Integer(), nullable=False),
    sa.Column('daily_shift_id', sa.Integer(), nullable=False),
    sa.Column('started_by_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('current_stage', sa.String(length=50), nullable=False),
    sa.Column('state_json', sa.Text(), nullable=True),
    sa.Column('issues_json', sa.Text(), nullable=True),
    sa.Column('conversation_history_json', sa.Text(), nullable=True),
    sa.Column('final_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_profile_id'], ['business_profiles.id'], ),
    sa.ForeignKeyConstraint(['daily_shift_id'], ['daily_shifts.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['chilling_temperature_incidents.id'], ),
    sa.ForeignKeyConstraint(['started_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', name='uq_chilling_temp_corrective_action_session_incident')
    )
    op.create_index(op.f('ix_chilling_temperature_corrective_action_sessions_business_profile_id'), 'chilling_temperature_corrective_action_sessions', ['business_profile_id'], unique=False)
    op.create_index(op.f('ix_chilling_temperature_corrective_action_sessions_current_stage'), 'chilling_temperature_corrective_action_sessions', ['current_stage'], unique=False)
    op.create_index(op.f('ix_chilling_temperature_corrective_action_sessions_daily_shift_id'), 'chilling_temperature_corrective_action_sessions', ['daily_shift_id'], unique=False)
    op.create_index(op.f('ix_chilling_temperature_corrective_action_sessions_id'), 'chilling_temperature_corrective_action_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_chilling_temperature_corrective_action_sessions_started_by_user_id'), 'chilling_temperature_corrective_action_sessions', ['started_by_user_id'], unique=False)
    op.create_index(op.f('ix_chilling_temperature_corrective_action_sessions_status'), 'chilling_temperature_corrective_action_sessions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chilling_temperature_corrective_action_sessions_status'), table_name='chilling_temperature_corrective_action_sessions')
    op.drop_index(op.f('ix_chilling_temperature_corrective_action_sessions_started_by_user_id'), table_name='chilling_temperature_corrective_action_sessions')
    op.drop_index(op.f('ix_chilling_temperature_corrective_action_sessions_id'), table_name='chilling_temperature_corrective_action_sessions')
    op.drop_index(op.f('ix_chilling_temperature_corrective_action_sessions_daily_shift_id'), table_name='chilling_temperature_corrective_action_sessions')
    op.drop_index(op.f('ix_chilling_temperature_corrective_action_sessions_current_stage'), table_name='chilling_temperature_corrective_action_sessions')
    op.drop_index(op.f('ix_chilling_temperature_corrective_action_sessions_business_profile_id'), table_name='chilling_temperature_corrective_action_sessions')
    op.drop_table('chilling_temperature_corrective_action_sessions')
    # ### end Alembic commands ###
